name: UWP Build

on: 
  push:
    branches: 
      - master

jobs:
  windows:
    strategy:
      matrix:
        os: [windows-2019]
        variant: [Release]
    runs-on: ${{ matrix.os }}
    name: UWP ${{ matrix.variant }} on ${{ matrix.os }}
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: '0'
      DEPOT_TOOLS_METRICS: '0'
      PYTHON_HOME: ''
    steps:
      - name: Check out source
        uses: actions/checkout@v1
      - name: Git Clone FAUDIO 
        shell: pwsh
        run: |
          dir
          mkdir FAudio
          dir
          git clone https://github.com/FNA-XNA/FAudio.git > out.txt
          dir
          cd FAudio
          dir
      - name: Archive ${{ matrix.variant }} UWP archive on ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: UWP Libraries for ${{ matrix.variant }} on ${{ matrix.os }}
          path: out.txt          
# TODO:
#   mercurial clone SDL2 (first)
#   figure out build command
#   git clone other libraries
#   build everything
#   grab DLLs and zip as asset
