name: UWP Build

on: 
  push:
    branches: 
      - master

jobs:
  windows:
    strategy:
      matrix:
        os: [windows-2019]
        variant: [Release]
    runs-on: ${{ matrix.os }}
    name: UWP ${{ matrix.variant }} on ${{ matrix.os }}
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: '0'
      DEPOT_TOOLS_METRICS: '0'
      PYTHON_HOME: ''
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0
      - name: Check out source
        uses: actions/checkout@v1
      - name: Hg Clone SDL2
        shell: cmd
        run: |
          mkdir SDL2
          hg clone http://hg.libsdl.org/SDL SDL2
      - name: Build SDL2
        shell: cmd
        run: MSBuild.exe "SDL2\VisualC-WinRT\UWP_VS2015\SDL-UWP.sln" /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142 /p:WindowsTargetPlatformVersion=10.0.16299.0 /p:WindowsTargetPlatformMinVersion=10.0.16299.0
      - name: Git Clone FAUDIO 
        shell: cmd
        run: |
          dir
          git clone https://github.com/FNA-XNA/FAudio.git
      - name: Build FAudio
        shell: cmd
        run: MSBuild.exe FAudio\visualc-winrt\FAudio.vcxproj /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142 /p:WindowsTargetPlatformVersion=10.0.16299.0;WindowsTargetPlatformMinVersion=10.0.16299.0
      - name: Archive ${{ matrix.variant }} UWP archive on ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: UWP Libraries for ${{ matrix.variant }} on ${{ matrix.os }}
          path: out.txt          
# TODO:
#   mercurial clone SDL2 (first)
#   figure out build command
#   git clone other libraries
#   build everything
#   grab DLLs and zip as asset
